-- Tabela de Fontes de Orçamento
CREATE TABLE `fontes_orcamento` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` varchar(20) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `tipo` enum('Federal','Estadual','Municipal','Emenda Parlamentar','Outro') NOT NULL,
  `descricao` text,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `fontes_orcamento_codigo_unique` (`codigo`),
  KEY `fontes_orcamento_created_by_foreign` (`created_by`),
  KEY `fontes_orcamento_updated_by_foreign` (`updated_by`),
  KEY `fontes_orcamento_deleted_by_foreign` (`deleted_by`),
  CONSTRAINT `fontes_orcamento_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fontes_orcamento_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fontes_orcamento_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabela de Categorias de Despesa
CREATE TABLE `categorias_despesa` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` varchar(20) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `descricao` text,
  `ativo` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categorias_despesa_codigo_unique` (`codigo`),
  KEY `categorias_despesa_created_by_foreign` (`created_by`),
  KEY `categorias_despesa_updated_by_foreign` (`updated_by`),
  KEY `categorias_despesa_deleted_by_foreign` (`deleted_by`),
  CONSTRAINT `categorias_despesa_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `categorias_despesa_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `categorias_despesa_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabela de Orçamentos
CREATE TABLE `orcamentos` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fonte_orcamento_id` bigint(20) UNSIGNED NOT NULL,
  `numero_orcamento` varchar(50) NOT NULL,
  `valor_total` decimal(15,2) NOT NULL DEFAULT '0.00',
  `valor_utilizado` decimal(15,2) NOT NULL DEFAULT '0.00',
  `ano_exercicio` year(4) NOT NULL,
  `descricao` text,
  `data_inicio` date DEFAULT NULL,
  `data_fim` date DEFAULT NULL,
  `parlamentar` varchar(255) DEFAULT NULL,
  `partido` varchar(50) DEFAULT NULL,
  `numero_convenio` varchar(50) DEFAULT NULL,
  `status` enum('Em Análise','Aprovado','Reprovado','Em Execução','Concluído','Cancelado') NOT NULL DEFAULT 'Em Análise',
  `observacoes` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `orcamentos_numero_orcamento_unique` (`numero_orcamento`),
  KEY `orcamentos_fonte_orcamento_id_foreign` (`fonte_orcamento_id`),
  KEY `orcamentos_created_by_foreign` (`created_by`),
  KEY `orcamentos_updated_by_foreign` (`updated_by`),
  KEY `orcamentos_deleted_by_foreign` (`deleted_by`),
  CONSTRAINT `orcamentos_fonte_orcamento_id_foreign` FOREIGN KEY (`fonte_orcamento_id`) REFERENCES `fontes_orcamento` (`id`),
  CONSTRAINT `orcamentos_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `orcamentos_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `orcamentos_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabela de Alocações de Orçamento
CREATE TABLE `alocacoes_orcamento` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `orcamento_id` bigint(20) UNSIGNED NOT NULL,
  `categoria_despesa_id` bigint(20) UNSIGNED NOT NULL,
  `processo_id` bigint(20) UNSIGNED DEFAULT NULL,
  `valor_alocado` decimal(15,2) NOT NULL DEFAULT '0.00',
  `valor_utilizado` decimal(15,2) NOT NULL DEFAULT '0.00',
  `data_empenho` date DEFAULT NULL,
  `numero_nota_empenho` varchar(50) DEFAULT NULL,
  `status` enum('Planejado','Empenhado','Liquidado','Pago','Cancelado') NOT NULL DEFAULT 'Planejado',
  `observacoes` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `alocacoes_orcamento_orcamento_id_foreign` (`orcamento_id`),
  KEY `alocacoes_orcamento_categoria_despesa_id_foreign` (`categoria_despesa_id`),
  KEY `alocacoes_orcamento_processo_id_foreign` (`processo_id`),
  KEY `alocacoes_orcamento_created_by_foreign` (`created_by`),
  KEY `alocacoes_orcamento_updated_by_foreign` (`updated_by`),
  KEY `alocacoes_orcamento_deleted_by_foreign` (`deleted_by`),
  CONSTRAINT `alocacoes_orcamento_orcamento_id_foreign` FOREIGN KEY (`orcamento_id`) REFERENCES `orcamentos` (`id`),
  CONSTRAINT `alocacoes_orcamento_categoria_despesa_id_foreign` FOREIGN KEY (`categoria_despesa_id`) REFERENCES `categorias_despesa` (`id`),
  CONSTRAINT `alocacoes_orcamento_processo_id_foreign` FOREIGN KEY (`processo_id`) REFERENCES `processos` (`id`),
  CONSTRAINT `alocacoes_orcamento_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `alocacoes_orcamento_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `alocacoes_orcamento_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabela de Movimentações de Orçamento
CREATE TABLE `movimentacoes_orcamento` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `alocacao_id` bigint(20) UNSIGNED NOT NULL,
  `tipo` enum('Empenho','Liquidação','Pagamento','Cancelamento') NOT NULL,
  `valor` decimal(15,2) NOT NULL DEFAULT '0.00',
  `numero_documento` varchar(50) DEFAULT NULL,
  `data_movimentacao` date NOT NULL,
  `observacoes` text,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_by` bigint(20) UNSIGNED DEFAULT NULL,
  `updated_by` bigint(20) UNSIGNED DEFAULT NULL,
  `deleted_by` bigint(20) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `movimentacoes_orcamento_alocacao_id_foreign` (`alocacao_id`),
  KEY `movimentacoes_orcamento_created_by_foreign` (`created_by`),
  KEY `movimentacoes_orcamento_updated_by_foreign` (`updated_by`),
  KEY `movimentacoes_orcamento_deleted_by_foreign` (`deleted_by`),
  CONSTRAINT `movimentacoes_orcamento_alocacao_id_foreign` FOREIGN KEY (`alocacao_id`) REFERENCES `alocacoes_orcamento` (`id`),
  CONSTRAINT `movimentacoes_orcamento_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `movimentacoes_orcamento_updated_by_foreign` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`),
  CONSTRAINT `movimentacoes_orcamento_deleted_by_foreign` FOREIGN KEY (`deleted_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
